services:
  scylladb:
    image: scylladb/scylla
    container_name: scylladb-mono
    healthcheck:
      test: ["CMD", "cqlsh", "-e", "SHOW VERSION"]
      interval: 5s
      retries: 10
      start_period: 20s
      timeout: 30s
    ports:
      - 9042:9042
    volumes:
      - scylladata:/var/lib/scylla
    networks:
      - hospitalsvc
  mainsvc:
    container_name: mainsvc
    build:
      context: ./
      dockerfile: Dockerfile
    environment:
      dbURL: scylladb:9042
    depends_on:
      scylladb:
        condition: service_healthy
    ports:
      - 8081:8081
    networks:
      - hospitalsvc
networks:
  hospitalsvc:
    driver: bridge

volumes:
  scylladata:
